name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Hostinger and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd public_html
            sleep 10
            npm install
            npm run build
            npx pm2 restart wlaa-site || npx pm2 start .next/standalone/server.js --name "wlaa-site" --port 3000
            npx pm2 save
